# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='_user_followed_+', to='social.User'),
        ),
    ]
